[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]

[phases.install]
cmds = ["cd server && npm install", "cd client && npm install"]

[phases.build]
cmds = ["cd server && npx prisma generate", "cd client && npm run build"]

[start]
cmd = "cd server && npx prisma db push && npm start"
