[build]
builder = "nixpacks"

[build.nixpacks]
providers = ["node"]

[deploy]
startCommand = "cd server && npx prisma migrate deploy && npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
